### ISSUE TITLE
Crashes when allyTeamIDs are not consecutive

### ISSUE THREAD

**Issue by mtroyka** [rlcevg/CircuitAI#1]
ie, if you set up ally teams such that it goes "1, 3, 4, 5" instead of "1, 2, 3, 4" circuit crashes at the load screen.

**Comment by rlcevg** [comment]
Crashes with ZK-Infra indeed. Thank you for report.

**Comment by rlcevg** [comment]
b1ef690bf591eb04d0dd3ef359255a5ad5e5c73e
