### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by abma** [rlcevg/CircuitAI#10]
AI/Skirmish/CircuitAI/src/circuit/module/MilitaryManager.h:124:104: error: array must be initialized with a brace-enclosed initializer
  std::array<float, static_cast<CCircuitDef::RoleT>(CCircuitDef::RoleType::TOTAL_COUNT)> enemyMetals{0.f};
                                                                                                        ^
AI/Skirmish/CircuitAI/src/circuit/module/MilitaryManager.h:129:104: error: array must be initialized with a brace-enclosed initializer
   std::array<float, static_cast<CCircuitDef::RoleT>(CCircuitDef::RoleType::TOTAL_COUNT)> roleMetals{0.f};

**Comment by rlcevg** [comment]
with gcc (GCC) 6.1.1 (damn arch linux - always rushing) all next options work:
```
* std::array(CCircuitDef::RoleType::TOTAL_COUNT)> roleMetals{0.f};
* std::array(CCircuitDef::RoleType::TOTAL_COUNT)> roleMetals{{0.f}};
* std::array(CCircuitDef::RoleType::TOTAL_COUNT)> roleMetals{};
```
Strange error. Array of floats not structs. What's the version of compiler (or what's prefered option)?
I'll double-check with windows (gcc 4.9)

**Comment by abma** [comment]
error is with gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2)

**Comment by rlcevg** [comment]
http://stackoverflow.com/questions/32912921/whats-wrong-with-this-inline-initialization-of-stdarray
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65815
https://github.com/rlcevg/CircuitAI/commit/d1ae19bb5a37dfaaac5c49c6b820651942755095
