### ISSUE TITLE
Check whether Sparrow broke circuit

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#100]
http://zero-k.info/Battles/Detail/723365

**Comment by rlcevg** [comment]
Everything seems ok.
The replay has too small window (2 minutes before game ends) to tell if there's a bug.
Possible explanation of what happened there: AI doesn't queue units if other factories builds something and resource pull is much greater than income (2-3x in case of replay), there was grizzly under construction that pulled most of the resources.

AI builds units only from the factory.json->factory->[name]->unit list. Hence it doesn't know about existence of sparrow (checked chobby's brutal config), just like amph factory still doesn't know about Lobster and works without it.

**Comment by rlcevg** [comment]
checked
