### ISSUE TITLE
Circuit AI crashes 104.0.1-1383-ga0129db

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#104]
https://github.com/ZeroK-RTS/CrashReports/issues/24074

**Comment by rlcevg** [comment]
energyfusion has no income_energy custom param, which is crucial to detect unit's energy production.
Broken game?

**Comment by rlcevg** [comment]
https://github.com/rlcevg/CircuitAI/commit/718c1bdf640657cf5fb4d6fe07a6cab4a2d8162f
