### ISSUE TITLE
A crash with 104.0.1-1432-gba1702d

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#105]
https://github.com/ZeroK-RTS/CrashReports/issues/25490

**Comment by rlcevg** [comment]
debug symbols of 1.0.5 are lost, and current dev branch is far from release state.
Options:
1) update ZK's circuit to latest stable 1.0.7 (known issue about triangulation of less than 3 vertices)
2) update to 1.0.6 (still has dbg symbols)

**Comment by GoogleFrog** [comment]
Do I just take circuit from the engine? Are there any config updates? Previously I was pulling PRs to chobby as they came up.

**Comment by rlcevg** [comment]
Yes, taking circuit dll from engine should work. There were no changes in config structure, so it should be safe to use current ZK's configs.

Last week i had no time to test before PR, probably can do it today or tomorrow.

**Comment by rlcevg** [comment]
https://github.com/ZeroK-RTS/Chobby/pull/718

**Comment by rlcevg** [comment]
outdated
