### ISSUE TITLE
Java Error on CMake

### ISSUE THREAD

**Issue by mmuetert** [rlcevg/CircuitAI#109]
Trying to make on Ubuntu 18.04. Encounter the following error:

Could NOT find Java (missing: Java_JAVAC_EXECUTABLE Java_JAVADOC_EXECUTABLE
  Development) (found version "11.0.10")

**Comment by rlcevg** [comment]
Unrelated to CircuitAI.
try `cmake -DAI_TYPES=NATIVE .`
