### ISSUE TITLE
Reproducible crash two seconds in to planet Karuwal on Normal.

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#111]
[DevCircuitAINormal64.zip](https://github.com/rlcevg/CircuitAI/files/6986849/DevCircuitAINormal64.zip)

https://github.com/ZeroK-RTS/CrashReports/issues/42169

[f=0000030] GoogleFrog unpaused the game
[f=0000077] Error: Spring 104.0.1-1544-ge1f249f maintenance has crashed.
[f=0000077] Error: DLL information:
[f=0000077] Error: 0x00400000	spring
[f=0000077] Error: 0x08a30000	ntdll
[f=0000077] Error: 0x07860000	KERNEL32
[f=0000077] Error: 0x06590000	KERNELBASE
[f=0000077] Error: 0x080f0000	ADVAPI32
[f=0000077] Error: 0x06d00000	msvcrt
[f=0000077] Error: 0x077c0000	sechost
[f=0000077] Error: 0x07fc0000	RPCRT4
[f=0000077] Error: 0x089d0000	imagehlp
[f=0000077] Error: 0x063e0000	ucrtbase
[f=0000077] Error: 0x08260000	SHELL32
[f=0000077] Error: 0x069f0000	msvcp_win
[f=0000077] Error: 0xf62e0000	GLU32
[f=0000077] Error: 0x055c0000	IPHLPAPI
[f=0000077] Error: 0x06ac0000	USER32
[f=0000077] Error: 0xdc210000	OPENGL32
[f=0000077] Error: 0x063b0000	win32u
[f=0000077] Error: 0x07ad0000	combase
[f=0000077] Error: 0x06a90000	GDI32
[f=0000077] Error: 0x068b0000	gdi32full
[f=0000077] Error: 0x08200000	SHLWAPI
[f=0000077] Error: 0x06f60000	WS2_32
[f=0000077] Error: 0x6b240000	libcurl
[f=0000077] Error: 0x061c0000	CRYPT32
[f=0000077] Error: 0x081a0000	WLDAP32
[f=0000077] Error: 0x62e80000	zlib1
[f=0000077] Error: 0x6a1c0000	libIL
[f=0000077] Error: 0x6b8c0000	libfreetype-6
[f=0000077] Error: 0x6b3c0000	libvorbisfile-3
[f=0000077] Error: 0x64f80000	libfontconfig-1
[f=0000077] Error: 0x6d540000	libvorbis-0
[f=0000077] Error: 0x6ed80000	glew32
[f=0000077] Error: 0x6c740000	SDL2
[f=0000077] Error: 0x089a0000	IMM32
[f=0000077] Error: 0x07690000	ole32
[f=0000077] Error: 0x07ef0000	OLEAUT32
[f=0000077] Error: 0x70680000	libogg-0
[f=0000077] Error: 0xfd9f0000	VERSION
[f=0000077] Error: 0xfd150000	WINMM
[f=0000077] Error: 0x68f40000	libexpat-1
[f=0000077] Error: 0x6b600000	OpenAL32
[f=0000077] Error: 0xbf5b0000	gameoverlayrenderer64
[f=0000077] Error: 0x06fd0000	PSAPI
[f=0000077] Error: 0x03bd0000	uxtheme
[f=0000077] Error: 0x07e30000	SHCORE
[f=0000077] Error: 0x07570000	MSCTF
[f=0000077] Error: 0x04090000	kernel.appcore
[f=0000077] Error: 0x48cd0000	bcryptPrimitives
[f=0000077] Error: 0x07460000	clbcatq
[f=0000077] Error: 0xa74a0000	nvoglv64
[f=0000077] Error: 0x06fe0000	SETUPAPI
[f=0000077] Error: 0x06860000	cfgmgr32
[f=0000077] Error: 0x069c0000	bcrypt
[f=0000077] Error: 0x01290000	WTSAPI32
[f=0000077] Error: 0x05d40000	msasn1
[f=0000077] Error: 0xfd940000	cryptnet
[f=0000077] Error: 0x05b30000	cryptbase
[f=0000077] Error: 0x05f00000	DEVOBJ
[f=0000077] Error: 0x06160000	WINTRUST
[f=0000077] Error: 0x04e60000	ntmarta
[f=0000077] Error: 0xfdb90000	dxcore
[f=0000077] Error: 0x04290000	windows.storage
[f=0000077] Error: 0x05bc0000	Wldp
[f=0000077] Error: 0x03da0000	dwmapi
[f=0000077] Error: 0x05730000	powrprof
[f=0000077] Error: 0x055a0000	UMPDC
[f=0000077] Error: 0x04ed0000	WINSTA
[f=0000077] Error: 0xfaf00000	textinputframework
[f=0000077] Error: 0x030d0000	CoreUIComponents
[f=0000077] Error: 0x037d0000	CoreMessaging
[f=0000077] Error: 0x020f0000	wintypes
[f=0000077] Error: 0x00e30000	MMDevApi
[f=0000077] Error: 0xdb850000	AUDIOSES
[f=0000077] Error: 0xfb270000	Windows.UI
[f=0000077] Error: 0x002a0000	WindowManagementAPI
[f=0000077] Error: 0xfada0000	InputHost
[f=0000077] Error: 0x00090000	twinapi.appcore
[f=0000077] Error: 0x008c0000	PROPSYS
[f=0000077] Error: 0xf2440000	dsound
[f=0000077] Error: 0xf3d60000	winmmbase
[f=0000077] Error: 0x03cb0000	resourcepolicyclient
[f=0000077] Error: 0xea410000	secur32
[f=0000077] Error: 0x06020000	SSPICLI
[f=0000077] Error: 0x05920000	mswsock
[f=0000077] Error: 0x07ee0000	NSI
[f=0000077] Error: 0x00350000	dhcpcsvc
[f=0000077] Error: 0xf5c80000	napinsp
[f=0000077] Error: 0xf5c60000	pnrpnsp
[f=0000077] Error: 0x013c0000	wshbth
[f=0000077] Error: 0x01f80000	NLAapi
[f=0000077] Error: 0x05610000	DNSAPI
[f=0000077] Error: 0xf5c40000	winrnr
[f=0000077] Error: 0xfd860000	fwpuclnt
[f=0000077] Error: 0xfd980000	rasadhlp
[f=0000077] Error: 0x56ac0000	AIInterface
[f=0000077] Error: 0x0f5a0000	SkirmishAI
[f=0000077] Error: 0xeb200000	dbghelp
[f=0000077] Error: Exception: Access violation (0xc0000005)
[f=0000077] Error: Exception Address: 0x000000010f632849
[f=0000077] Error: Stacktrace for Spring 104.0.1-1544-ge1f249f maintenance:
[f=0000077] Error: This stacktrace indicates a problem with a skirmish AI.
[f=0000077] Error: 	[ProgCtr=000000010f632849 StackPtr=000000004329a030 FramePtr=00000000f18ff7e0]
[f=0000077] Error: 	(0) F:\Steam\steamapps\common\Zero-K\AI\Skirmish\DevCircuitAINormal64\stable\SkirmishAI.dll [0x00092849]
[f=0000077] Error: 	(1) F:\Steam\steamapps\common\Zero-K\AI\Skirmish\DevCircuitAINormal64\stable\SkirmishAI.dll [0x00096FD3]
[f=0000077] Error: 	(2) F:\Steam\steamapps\common\Zero-K\AI\Skirmish\DevCircuitAINormal64\stable\SkirmishAI.dll [0x0009ED2C]
[f=0000077] Error: 	(3) F:\Steam\steamapps\common\Zero-K\AI\Skirmish\DevCircuitAINormal64\stable\SkirmishAI.dll [0x000032A0]
[f=0000077] Error: 	(4) F:\Steam\steamapps\common\Zero-K\AI\Skirmish\DevCircuitAINormal64\stable\SkirmishAI.dll [0x00003E71]
[f=0000077] Error: 	(5) F:\Steam\steamapps\common\Zero-K\AI\Skirmish\DevCircuitAINormal64\stable\SkirmishAI.dll [0x00008044]
[f=0000077] Error: 	(6) F:\Steam\steamapps\common\Zero-K\AI\Skirmish\DevCircuitAINormal64\stable\SkirmishAI.dll [0x00001556]
[f=0000077] Error: 	(7) F:\Steam\steamapps\common\Zero-K\engine\win64\104.0.1-1544-ge1f249f\spring.exe [0x00865097]
[f=0000077] Error: 	(8) F:\Steam\steamapps\common\Zero-K\engine\win64\104.0.1-1544-ge1f249f\spring.exe [0x00868BE8]
[f=0000077] Error: 	(9) F:\Steam\steamapps\common\Zero-K\engine\win64\104.0.1-1544-ge1f249f\spring.exe [0x008690B7]
[f=0000077] Error: 	(10) F:\Steam\steamapps\common\Zero-K\engine\win64\104.0.1-1544-ge1f249f\spring.exe [0x00844730]
[f=0000077] Error: 	(11) F:\Steam\steamapps\common\Zero-K\engine\win64\104.0.1-1544-ge1f249f\spring.exe [0x0042B0FB]
[f=0000077] Error: 	(12) F:\Steam\steamapps\common\Zero-K\engine\win64\104.0.1-1544-ge1f249f\spring.exe [0x00516B51]
[f=0000077] Error: 	(13) F:\Steam\steamapps\common\Zero-K\engine\win64\104.0.1-1544-ge1f249f\spring.exe [0x004313B9]
[f=0000077] Error: 	(14) F:\Steam\steamapps\common\Zero-K\engine\win64\104.0.1-1544-ge1f249f\spring.exe [0x007CFAFA]
[f=0000077] Error: 	(15) F:\Steam\steamapps\common\Zero-K\engine\win64\104.0.1-1544-ge1f249f\spring.exe [0x007D2DD8]
[f=0000077] Error: 	(16) F:\Steam\steamapps\common\Zero-K\engine\win64\104.0.1-1544-ge1f249f\spring.exe [0x007BE9EB]
[f=0000077] Error: 	(17) F:\Steam\steamapps\common\Zero-K\engine\win64\104.0.1-1544-ge1f249f\spring.exe [0x00D6C35F]
[f=0000077] Error: 	(18) F:\Steam\steamapps\common\Zero-K\engine\win64\104.0.1-1544-ge1f249f\spring.exe [0x004013BD]
[f=0000077] Error: 	(19) F:\Steam\steamapps\common\Zero-K\engine\win64\104.0.1-1544-ge1f249f\spring.exe [0x004014CB]
[f=0000077] Error: 	(20) C:\WINDOWS\System32\KERNEL32.DLL [0x00017034]
[f=0000077] Error: 	(21) C:\WINDOWS\SYSTEM32\ntdll.dll [0x00052651]
[f=0000077] [WatchDog::DeregisterThread] deregistering controls for thread [main]
[f=0000077] Error: [ExitSpringProcess] errorMsg="Spring has crashed:
  Access violation.

**Comment by rlcevg** [comment]
https://github.com/rlcevg/CircuitAI/commit/cd5a766cafc739936d9435026376f7215a1ebd88
