### ISSUE TITLE
Strider Hub is idle for a long time

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#112]
![image](https://user-images.githubusercontent.com/1318249/144739845-90934c28-c88d-47e9-85b6-85fb00d4c17f.png)

https://zero-k.info/Battles/Detail/1252200

I'm not sure that the strider hub should be idle for minutes on end. It works earlier in the game.

**Comment by rlcevg** [comment]
https://github.com/rlcevg/CircuitAI/commit/596a0a8974f18e6485aa613fdb96d75d55838915
https://github.com/rlcevg/CircuitAI/commit/a762d1fb11e61b4e233d8e4a5b013fd9cd694d09
