### ISSUE TITLE
Barbarian AI crash after load in Beyond All Reason

### ISSUE THREAD

**Issue by Svalorzen** [rlcevg/CircuitAI#114]
Please apologize if this is not the correct place to create this issue, let me know if there's a better place for it.

I have a BAR savefile of a scenario. When I load it, and I progress a little bit more in the scenario, the game consistently crashes. The `infolog.txt` reports some `C++` errors from `../AI/Skirmish/BARb/stable/libSkirmishAI.so`, which I assume should be this repo.

For now I'm adding here the `infolog.txt` file, do let me know if you need something more.

I launch BAR from Ubuntu, and my current appimage file is called `Beyond-All-Reason-1.1459.0.AppImage`.
[infolog.txt](https://github.com/rlcevg/CircuitAI/files/8548632/infolog.txt)

**Comment by rlcevg** [comment]
just waiting for the next engine version release, fix should be included there.
