### ISSUE TITLE
make it work with latest develop

### ISSUE THREAD

**Issue by cleanrock** [rlcevg/CircuitAI#17]
Even if latest spring/develop is a bit of a mess atm it would be nice if you could make it work with it.

[f=-000001] Loading Skirmish AIs
[SharedLibrary.c::sharedLib_load(/home/johanr/spring_develop/share/games/spring/AI/Skirmish/CircuitAI/0.9.10/libSkirmishAI.so)] dlopen() error /home/johanr/spring_develop/share/games/spring/AI/Skirmish/CircuitAI/0.9.10/libSkirmishAI.so: undefined symbol: _ZN12spring_futexD1Ev
[f=-000001] [C Interface] Error: Failed loading shared library: /home/johanr/spring_develop/share/games/spring/AI/Skirmish/CircuitAI/0.9.10/libSkirmishAI.so
[f=-000001] Error: Skirmish AI CircuitAI-0.9.10 not found!
The game will go on without it.
This usually indicates a problem in the used AI Interface library (-),
or the Skirmish AI library is not in the same place as its AIInfo.lua.

**Comment by rlcevg** [comment]
Fix: https://github.com/rlcevg/CircuitAI/commit/020ae9607a67ec14d962aaeba4b6c8cebd94e64a
