### ISSUE TITLE
Obey disabled units

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#20]
Circuit ignores the removal or disabling of commands from units build menus. If the commanders are blocked in AllowCommand or AllowUnitCreation then the AI does not adapt, it just sits there and does nothing. I've implemented locks again, see: https://github.com/ZeroK-RTS/Zero-K/commit/d3c31548a69caf78b09a586bf246255f3da89b67

In case AIs cannot read the fact that commands are missing or disabled I added TeamRulesParam unlockedUnitCount. If unlockedUnitCount is set (non-nil) then there is a limited set of units unlocked. These units are by unit def name and are stored in the TeamRulesParams unlockedUnit1, unlockedUnit2, ..., unlockedUnit<unlockedUnitCount>.

**Comment by GoogleFrog** [comment]
I'm aware that I can probably already do this with the AIOption 'config' although doing it this way sounds insane.

**Comment by GoogleFrog** [comment]
Does 'config' work? I have not been able to get it to work because startscripts cannot include raw json and expect to be parsed correctly by Spring.

**Comment by GoogleFrog** [comment]
The source seems to say that the config key expects a file name, not a file. This isn't use useful as I thought. Perhaps an option could be added that accepts a base64 encoding of a json string as its config. I know that those can be snuck through starscripts.

However, this is getting insane. The conversion of the config would then be json -> lua -> json -> base64 -> json.

**Comment by GoogleFrog** [comment]
The unlocked units will not change throughout the game so I could send them as a nice string into aiOptions. Perhaps comma separated unitDefNames?

**Comment by rlcevg** [comment]
So what's the format of aiOption? Something like
```
disabledunits=raveparty,zenith,mahlaze
```

NOTE: Current stable release supports [!setoptions disabledunits=raveparty+zenith+mahlaze](https://github.com/rlcevg/CircuitAI/blob/0fd548daccc76665ae89e8d1a6304da9c2382b7d/src/circuit/setup/SetupManager.cpp#L61).
Or config through ["json" aiOption](https://github.com/rlcevg/CircuitAI/blob/0fd548daccc76665ae89e8d1a6304da9c2382b7d/src/circuit/setup/SetupManager.cpp#L90)

**Comment by GoogleFrog** [comment]
Sure, that format works. I have not written any format so you can do whatever reasonable thing you want.

You've already got a + separated string function so I could use + instead of ,.

**Comment by rlcevg** [comment]
https://github.com/rlcevg/CircuitAI/tree/a7b0a4df161b0380925edb71ed85b8b668fd2cbe
Syntax of AIOption:
```
disabledunits=armwar+tele_beacon+armpw+raveparty+zenith+mahlazer;
```
