### ISSUE TITLE
Feature: Ignoring certain units

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#21]
I would like to be able to disable/enable AI control of particular units with a gadget. I would set a UnitRulesParam on the unit and give it orders directly with the gadget. When the unit is back to being controlled by the AI the UnitRulesParam would be removed.

**Comment by rlcevg** [comment]
Minor polling option:
AI API has EVENT_PLAYER_COMMAND being sent when something gives command to unit that belongs to AI. Event decriptor has list of units. On this event AI will start to ignore those units and check every 1-3 seconds their UnitRulesParam (==1). When UnitRulesParam is unset (!=1) AI starts to give commands again.

**Comment by GoogleFrog** [comment]
Sounds good. I don't know what the API event is but I assume ZK already uses it somehow.

**Comment by rlcevg** [comment]
What's the name of UnitRulesParam? Is it already exists in ZK gadgets?

**Comment by GoogleFrog** [comment]
No, none of this exists gameside.

**Comment by rlcevg** [comment]
https://github.com/rlcevg/CircuitAI/commit/e6289b01016419dd3af9beb12b98429b08c96328
Let the UnitRulesParam be "player_control". If it's 1 **_and_** player gave command to unit then AI stops giving orders to it. If "player_control" is not 1 or unset then AI takes control back.

**Comment by GoogleFrog** [comment]
What do you mean by player? I want to give commands with a gadget.

**Comment by rlcevg** [comment]
Nice question, i expect EVENT_PLAYER_COMMAND to be any command not from AI. But i should check it in engine sources.

**Comment by rlcevg** [comment]
Apparantly there are no events for gadget, and unit commands from gadget doesn't produce NETMSG_COMMAND.
Then the best for AI performance is to send handmade events via gadget:
```
Spring.SendSkirmishAIMessage(aiTeamID, 'DISABLE_UNIT:unitID1+unitID2+unitID3')
Spring.SendSkirmishAIMessage(aiTeamID, 'ENABLE_UNIT:unitID1+unitID2+unitID3')
```
See gadget [METAL_SPOTS](https://github.com/ZeroK-RTS/Zero-K/blob/88a1e1f2fa2a5b63a807b1472ea9d9925155d051/LuaRules/Gadgets/mex_spot_finder.lua#L470) event for example.
That way AI can disable control the very same frame the message was sent.

Otherwise with UnitRulesParam AI will have to poll every unit. And with staggered polling it make take 1-5 seconds before unit will be disabled or enabled.

**Comment by ashdnazg** [comment]
do AIs get some sort of callins?

**Comment by rlcevg** [comment]
[Spring.SendSkirmishAIMessage](https://github.com/ZeroK-RTS/Zero-K/blob/88a1e1f2fa2a5b63a807b1472ea9d9925155d051/LuaRules/Gadgets/mex_spot_finder.lua#L470) => [EVENT_LUA_MESSAGE](https://github.com/rlcevg/CircuitAI/blob/e6289b01016419dd3af9beb12b98429b08c96328/src/circuit/CircuitAI.cpp#L340)
But it seems [unsynced only](https://github.com/spring/spring/blob/f9c2d0555e93f2208c5015d0d6197c5badbfad62/rts/Lua/LuaUnsyncedCtrl.cpp#L2849), so my assumption about the very same frame is wrong. Is there a way to send unsynced from synced?
Or if 1-5 seconds delay doesn't matter then i'll go with staggered UnitRulesParam polling.

**Comment by rlcevg** [comment]
GoogleFrog mentioned GameRulesParam (well, TeamRulesParam fits better).
It's possible to poll "brain_wash" TeamRulesParam each frame.
```
"brain_wash":"unitID1+unitID2+unitID3"
```
But then after 1st washing previous value of param must be saved and compared with current value to identify changes... Not very efficient.

Yet another option: check "brain_wash" UnitRulesParam before giving orders or assigning task to unit.

**Comment by Anarchid** [comment]
It should be possible to send data from gadget synced to gadget unsynced with SendToUnsynced. 

Then the unsynced part relay to SendSkirmishAIMessage.

**Comment by rlcevg** [comment]
Ok, going with ```SendSkirmishAIMessage```
Here's gadget example that spawns AI units at 20th second, disables them and gives attack order, then returns units to AI at 2nd minute:
```lua
function gadget:GetInfo()
  return {
    name      = "Test disabling",
    desc      = "Test",
    author    = "fatso",
    date      = "22 Feb 2017",
    license   = "public domain",
    layer     = 0,
    enabled   = true  --  loaded by default?
  }
end

--------------------------------------------------------------------------------
-- SYNCED
--------------------------------------------------------------------------------
if gadgetHandler:IsSyncedCode() then

local GiveClampedOrderToUnit = Spring.Utilities.GiveClampedOrderToUnit

local disablees = {}

function gadget:GameFrame(gameFrame)
	if (gameFrame == 600) then  -- 20th second; Create unit and disable AI control

		local teamlist = Spring.GetTeamList()
		for _, teamID in pairs(teamlist) do
			-- Create units only for AI
			local _,_,_,isAI = Spring.GetTeamInfo(teamID)
			if isAI then

				Spring.Echo("Team:" .. tostring(teamID) .. " | gameFrame0: " .. tostring(gameFrame))

				local newUnits = {}
				for i = 1, 5 do  -- Spawn 5 new units
					x = math.random(100, Game.mapSizeX - 100)
					z = math.random(100, Game.mapSizeZ - 100)
					y = Spring.GetGroundHeight(x, z)
					local unitID = Spring.CreateUnit("armpw", x, y, z, "n", teamID)
					GiveClampedOrderToUnit(unitID, CMD.ATTACK, {x+100, y, z+100}, {"alt"})
					table.insert(newUnits, unitID)
				end
				disablees[teamID] = newUnits

				Spring.Echo("Team:" .. tostring(teamID) .. " | gameFrame1: " .. tostring(gameFrame))

				local dis_msg = "DISABLE_UNIT:"
				for _, unitID in pairs(newUnits) do
					dis_msg = dis_msg .. tostring(unitID) .. "+"
				end
				SendToUnsynced('SendAIEvent', teamID, dis_msg)

				Spring.Echo("Team:" .. tostring(teamID) .. " | gameFrame2: " .. tostring(gameFrame))
			end
		end

	elseif (gameFrame == 3600) then  -- 2nd minute; Enable AI control of created unit

		for teamID, spawnUnits in pairs(disablees) do
			Spring.Echo("Team:" .. tostring(teamID) .. " | gameFrame3: " .. tostring(gameFrame))

			local en_msg = "ENABLE_UNIT:"
			for _, unitID in pairs(spawnUnits) do
				en_msg = en_msg .. tostring(unitID) .. "+"
			end
			SendToUnsynced('SendAIEvent', teamID, en_msg)

			Spring.Echo("Team:" .. tostring(teamID) .. " | gameFrame4: " .. tostring(gameFrame))
		end
	end
end

function gadget:UnitCreated(unitID, unitDefID, teamID)
	Spring.Echo("Team:" .. tostring(teamID) .. " | gadget:UnitCreated " .. tostring(unitID))
end

function gadget:UnitFinished(unitID, unitDefID, teamID)
	Spring.Echo("Team:" .. tostring(teamID) .. " | gadget:UnitFinished " .. tostring(unitID))
end

--------------------------------------------------------------------------------
else  -- UNSYNCED
--------------------------------------------------------------------------------

function gadget:Initialize()
	gadgetHandler:AddSyncAction('SendAIEvent', SendAIEvent)
end

function SendAIEvent(_, teamID, msg)
	local localPlayer = Spring.GetLocalPlayerID();
	-- Send message only to hosted native AI
	local aiid, ainame, aihost = Spring.GetAIInfo(teamID);
	if (aihost == localPlayer) then
		Spring.Echo("Team:" .. tostring(teamID) .. " | SendAIEvent0 | " .. msg)
		Spring.SendSkirmishAIMessage(teamID, msg)
		Spring.Echo("Team:" .. tostring(teamID) .. " | SendAIEvent1 | END")
	end
end

end
```

**Comment by rlcevg** [comment]
https://github.com/rlcevg/CircuitAI/commit/03e90a69bafd0f3138e404a4a25cbbdcf8358f7f
