### ISSUE TITLE
Crash after warnings

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#25]
https://github.com/ZeroK-RTS/CrashReports/issues/82

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/CrashReports/issues/76

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/CrashReports/issues/74

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/CrashReports/issues/66

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/CrashReports/issues/61

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/CrashReports/issues/58

**Comment by rlcevg** [comment]
Fixed in https://github.com/rlcevg/CircuitAI/commit/e1b64a065223f142f4eeaaefa8ba4c28e8c64935
Except #66.

**Comment by GoogleFrog** [comment]
More crash after warnings https://github.com/ZeroK-RTS/CrashReports/issues/138

**Comment by rlcevg** [comment]
Can't reproduce #138 or understand why crash happens inside [std::_Rb_tree_rebalance_for_erase](https://github.com/rlcevg/CircuitAI/blob/17195b167cd12a07962a5b2081395d7909f30951/src/circuit/module/EconomyManager.cpp#L372).
But every leak and heap-buffer-overflow reported by AddressSanitizer were fixed, and my guess is #138 was a consequance of memory leaks.

**Comment by GoogleFrog** [comment]
Two more:
https://github.com/ZeroK-RTS/CrashReports/issues/159
https://github.com/ZeroK-RTS/CrashReports/issues/138

**Comment by rlcevg** [comment]
#159 is fixed, and about #138 (a.k.a. #66) see my previous post.

**Comment by GoogleFrog** [comment]
Crash https://github.com/ZeroK-RTS/CrashReports/issues/185

**Comment by rlcevg** [comment]
Common thing in crashes #66, #138, #185 is speedmetal maps:
SuperSpeedMetal, Mini_SuperSpeedMetal.

**Comment by rlcevg** [comment]
#66, #138, #185: https://github.com/rlcevg/CircuitAI/commit/9418bad74d1d824e9d334c53176c305756c07a88
