### ISSUE TITLE
Latest Circuit AI crash

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#34]
I added all four circuit AIs to a battle and spring froze within a few seconds.

[infolog.txt](https://github.com/rlcevg/CircuitAI/files/921631/infolog.txt)

**Comment by GoogleFrog** [comment]
The crash may have been because there were planetwars structures spawned on the map. Circuit still shouldn't crash when unusual structures appear.

**Comment by rlcevg** [comment]
Theory: builder of building wasn't real builder, or rather Circuit doesn't recognize that unit as builder with valid buildOptions.
Need more nullptr checks.

**Comment by rlcevg** [comment]
Here goes trial&error: https://github.com/rlcevg/CircuitAI/commit/83eb7ea3ccd1bf96137b734b1248b4ad9a819036
If crashes with non-default missions will continue then i need some way to run/reproduce those missions.
