### ISSUE TITLE
Actual very easy mode

### ISSUE THREAD

**Issue by db81** [rlcevg/CircuitAI#37]
How hard is it to implement something like ZeroK-RTS/Zero-K#2179 in Circuit? Would it be a lot of work? It would involve disabling most clever things Circuit does, like porc avoidance, retreat to repair, not excessing all of your metal, and I don't know how deeply those are wired in.

**Comment by Anarchid** [comment]
Highly cowardly retreat of entire squads actually gives the player more breathing room, imo. Removing retreat will cause attackers to fight tooth and nail, the KGB approach.

**Comment by db81** [comment]
That denies the newbie the satisfaction of watching the enemy getting blown to pieces. It also makes the AI amass units, which is the opposite of what we want. The idea is to send stuff that will die to an HLT anyway, and to do that indefinitely without escalating. So doesn't matter if that 3 zeus army fights tooth-and-nail, it's getting nailed to the wall.

**Comment by rlcevg** [comment]
It's possible to make easier config (**excess** ratio is real): [my lazy quick-try](http://paste.springfiles.com/view/939661ab). But not enough test subjects, and interest in making AI dummier.
Controlling maximum group size and time intervals between attacks is not possible with 0.9.15 though.

Current Easy and Medium configs may have misconfigured attack-group params after update 0.9.13->0.9.15

**Comment by DeinFreund** [comment]
These params sound good. Would you be able to release a new version with them?

**Comment by rlcevg** [comment]
Will look into #49 and #50 and hopefully release new version soon.

**Comment by GoogleFrog** [comment]
Thanks for those parameters, I think this can be closed.

**Comment by rlcevg** [comment]
Currently (easy) configs mostly maintained/upgraded by 3rd party (Ivory_King, GoogleFrog, others?).
