### ISSUE TITLE
Crash when loading a save game

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#38]
https://github.com/ZeroK-RTS/CrashReports/issues/820

**Comment by rlcevg** [comment]
How to save/load? How can i reproduce it?

**Comment by GoogleFrog** [comment]
Save/load with the save/load menu in the F10 menu in ZK.

**Comment by rlcevg** [comment]
I haven't encountered crashes on save/load. Also could be resolved as duplicate as https://github.com/rlcevg/CircuitAI/issues/36, because there's simply no save/load handling at the moment.
