### ISSUE TITLE
Failure to load on dev engine

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#39]
You may want to provide input here: https://springrts.com/mantis/view.php?id=5540

**Comment by rlcevg** [comment]
Summary: recompile AI.

**Comment by GoogleFrog** [comment]
Please don't do that first, I want to update the engine.

**Comment by rlcevg** [comment]
Mantis' ticket has wrong infolog.txt
And i can't reproduce on linux - old AI works with latest engine. Poor windows.
Still recompiling...

**Comment by GoogleFrog** [comment]
Did you recompile using the latest spring? Your PR did not fix it.

**Comment by rlcevg** [comment]
I was unable to reproduce it in 1v1, 103.0.1-877-g9eb8948, old 0.9.15 or new 0.9.15.a.

**Comment by GoogleFrog** [comment]
ok I'll look again.
