### ISSUE TITLE
Check internal unit name rename compatibility

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#40]
Many of the internal names of the ZK units have been changed for improved consistency. The branch is here: https://github.com/ZeroK-RTS/Zero-K/tree/internalrename

Here is a complete list of the changes: https://github.com/ZeroK-RTS/Zero-K/issues/1596#issuecomment-298212175

While doing the changes we included the circuit configs and changed the unit names with with the same find/replace. The modified configs are here: https://github.com/ZeroK-RTS/Zero-K/tree/internalrename/AI

I am going to update the configs in chobby manually, probably by next Tuesday looking at my schedule. Development circuit should use the new configs once they are tested. If circuit has hardcoded internal unit names anywhere then it is likely to require a release.

**Comment by rlcevg** [comment]
Thanks for info!
Transition should be smooth (in theory), one of the main goal of config was to get rid of all hardcoded unitnames.

**Comment by rlcevg** [comment]
ZK was updated to v1.5.5.0
Circuit seems to work in general.
