### ISSUE TITLE
Consider CMD_RAW_MOVE

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#43]
Players barely give CMD.MOVE commands anymore in ZK since it has been replaced with CMD_RAW_MOVE. This replacement move command causes units to move directly in a direction, without invoking the pathfinder, if the direct path is free.

I have noticed that circuit games have high sim::path in profiling, around 9%. Circuit seems to primarily issue very short move orders and implement its own pathfinding so perhaps it would run smoother with CMD_RAW_MOVE.

**Comment by rlcevg** [comment]
https://github.com/rlcevg/CircuitAI/commit/2d3274e198152d0f0e916dec697a07e67292f521
Used CMD_RAW_MOVE as much as it's currently possible. Although i didn't notice difference.
