### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#44]
https://github.com/ZeroK-RTS/CrashReports/issues/1121

**Comment by rlcevg** [comment]
When totally broken config happens (infolog informs about it) "Good fun, have luck!" should be replaced by "Fix your config!"
"Starting detonation sequence!"
"5 ... 4 ... 3"
"Hurry up!"
"2 ... 1"
AI shutdown.

**Comment by rlcevg** [comment]
https://github.com/rlcevg/CircuitAI/commit/2d3274e198152d0f0e916dec697a07e67292f521
