### ISSUE TITLE
[f=0016174] Warning: AI for team 1 (ID: 0) failed handling event with topic 9, error: 209

### ISSUE THREAD

**Issue by abma** [rlcevg/CircuitAI#45]
https://github.com/ZeroK-RTS/CrashReports/issues/1166

**Comment by abma** [comment]
upstream bug report: https://springrts.com/mantis/view.php?id=5576

**Comment by rlcevg** [comment]
This should be another mantis ticket for spring:
Engine sends UnitDamaged after UnitDestroyed

**Comment by rlcevg** [comment]
The minimum code to reproduce (CppTestAI) is still available in https://springrts.com/mantis/view.php?id=5576 ticket
