### ISSUE TITLE
can't be run when started via ./spring

### ISSUE THREAD

**Issue by abma** [rlcevg/CircuitAI#46]
compile latest spring develop + circuitai, start ./spring
select zero-k 1.5.5.1 + some map + CircuitAI

->
[f=-000001] Skirmish AI <Circuit-stable>: Missing config file! (LuaRules/Configs/CircuitAI/stable/DeltaSiegeDry.json)
[f=-000001] Skirmish AI <Circuit-stable>: Missing config file! (LuaRules/Configs/CircuitAI/stable/Default/circuit.json)
[f=-000001] Skirmish AI <Circuit-stable>: Config file is missing! (circuit.json)
<CircuitAI DEBUG> Execute: int circuit::CCircuitAI::Release(int)
[f=-000001] Warning: AI for team 1 (ID: 0) failed handling event with topic 1, error: 201
[f=-000001] Error: Failed to handle init event: AI for team 1, error 201

**Comment by rlcevg** [comment]
According to
[f=-000001] Skirmish AI : Config file is missing! (circuit.json)
it can't see default config.json
AI folder of an engine should look like this:
```
103.0.1-939-g2b3f9469a
    |-AI/
        |-Skirmish/
            |-CircuitAI/
                |-stable/
                    |-config/
                        |-circuit.json    <- this thing matters
                    |-AIInfo.lua
                    |-AIOptions.lua
                    |-libSkirmishAI.so
    |-base/
    |-cache/
  ...
```
I don't know what's "make spring-install" doing, never used it.
Another idea is that maybe SpringData from springsettings.cfg points into wrong location.

**Comment by abma** [comment]
thanks for the hint.

cd AI/Skirmish/CircuitAI && mkdir stable && mkdir -p stable/ && ln -s data/config/ stable/
made it work to run from an in-source build.

can 
AI/Skirmish/CircuitAI/data/config/circuit.json

be added as fallback searchpath for the config? this allows much easier testing.

**Comment by abma** [comment]
afaik make install-spring should copy data/* to AI/Skirmish/CircuitAI/ in the install dir.

**Comment by rlcevg** [comment]
Added ```AI/Skirmish/<AI_name>/data/config/``` as fallback config location.
I probably could just rename version "stable" into "data", but don't want to mess with ZK's AI upgrade system.
https://github.com/rlcevg/CircuitAI/commit/6b68af26c0097e751658d3e638aaf812fbc31833
