### ISSUE TITLE
Add a factory grace time parameter

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#52]
There is a remaining minor issue with the very easy config: circuit can send scouts at the player within the first few minutes of the game. I do not want to disable scouting or raiding because it is good to poke the player with lone cheap units once they have a bit of defense. The only issue is that the units appear too early, they can disrupt the players attempt to figure things out.

The simplest way to fix this would be with a parameter that prevents factory production for the first X seconds. I would probably set it at around 6 minutes to ensure that the player first encounters opposition at around 8-10 minutes unto the game.

**Comment by rlcevg** [comment]
Implemented through https://github.com/rlcevg/CircuitAI/issues/57 on per-unit basis
