### ISSUE TITLE
match to analyze for inefficiency

### ISSUE THREAD

**Issue by cleanrock** [rlcevg/CircuitAI#54]
http://zero-k.info/Battles/Detail/462937

Very odd behaviour, wasted a lot of metal and could have won much earlier.

**Comment by rlcevg** [comment]
1) caretaker per factory value is too high. Factories have delay (just like spring's unit update cycle) before executing new order plus time for the low cost units to move away out of factory.
2) factories "under threat" doesn't build anything. Seen in the end of the game when bantha/catapult goes in 2D range of shot to amph factory - it starts idling. (probably this safety measure should be removed)

**Comment by cleanrock** [comment]
Metal Excess was ~220k (21 Bantha).
Com morphed to level 26 which i guess it is what circuit do when it is trying to reduce metal excess.
Great if you can add something to reduce metal excess in games like this.
Thanks for taking your time to watch this match.

**Comment by rlcevg** [comment]
3) batch production (what Ivory_King asked long time ago) - should reduce pause between build orders.
4) variable additional percent of factory buildpower over income. Currently it's hardcoded to 20%, but it probably should stay low with low metal-income and get higher with high metal-income.

All of those options should address excess issue.

**Comment by rlcevg** [comment]
Some things were improved. Current match is outdated.
