### ISSUE TITLE
Spawning units in GamePreload crashes circuit

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#56]
If you spawn units in gadget:GamePreload circuit crashes. It would be really good if this worked because it would remove some slowness from loading missions at the start of the game. 

Stacktrace at the end: https://github.com/ZeroK-RTS/CrashReports/issues/1582

**Comment by rlcevg** [comment]
It does work:
```
function gadget:GetInfo()
  return {
    name      = "Test unit",
    desc      = "Test",
    author    = "fatso",
    date      = "04 Mar 2017",
    license   = "public domain",
    layer     = 0,
    enabled   = true  --  loaded by default?
  }
end

--------------------------------------------------------------------------------
-- SYNCED
--------------------------------------------------------------------------------
if gadgetHandler:IsSyncedCode() then

--function gadget:Initialize()
function gadget:GamePreload()
	x = math.random(100, 2000)
	z = math.random(100, 2000)
	y = Spring.GetGroundHeight(x, z)
	local unitID = Spring.CreateUnit("factorycloak", x, y, z, "n", 0)
	Spring.Echo("gadget:GamePreload " .. tostring(unitID))
end

function gadget:UnitCreated(unitID, unitDefID, teamID)
	Spring.Echo("Team:" .. tostring(teamID) .. " | gadget:UnitCreated " .. tostring(unitID))
end

function gadget:UnitFinished(unitID, unitDefID, teamID)
	Spring.Echo("Team:" .. tostring(teamID) .. " | gadget:UnitFinished " .. tostring(unitID))
end

end 
```

In other words: how to reproduce?
I suspect mission has some undefined custom unitdefs.

**Comment by GoogleFrog** [comment]
Run this startscript. You need 
 * Tabula-v6.1, although changing it shouldn't matter.
 * Zero-K $VERSION, or to replace the version in the start script with a test version after https://github.com/ZeroK-RTS/Zero-K/commit/a3ea7de3da45c3df9a17aa7ef0902d8c991c024e.
 * CircuitAIMedium32, or to replace the two times it appears with a circuit of your choice.

[scriptFile.txt](https://github.com/rlcevg/CircuitAI/files/1168641/scriptFile.txt)

**Comment by rlcevg** [comment]
Got it. Not sure how it's possible: i expected engine to raise AI's UnitCreated event for each Spring.CreateUnit consequentially. But in reality engine's GetFriendlyUnitsIn may return yet unregistered by AI units.
Quickfix is to ignore yet unregistered by AI units.

**Comment by rlcevg** [comment]
There's another issue: UnitFinished called twice for some units, that leads to memory-leak and access violation.

**Comment by rlcevg** [comment]
https://github.com/rlcevg/CircuitAI/commit/319d70578329184507687f43b1dc87a63a25a24b
