### ISSUE TITLE
Add per-unit time limit

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#57]
I'd like every unit to have a parameter which limits how many minutes must pass before circuit tries to make the unit. This would be similar to the current unit limit parameter, just for time. This would allow an AI to start off artificially easy but have a fully fleshed out army once the game has continued for longer.

This could be used to implement https://github.com/rlcevg/CircuitAI/issues/52 so is the more general request.

**Comment by rlcevg** [comment]
https://github.com/rlcevg/CircuitAI/commit/4969ab9aabdf0c5809f34aa0f161bad506fdfc75
