### ISSUE TITLE
CircuitAI gets trapped by allied factory on small map 

### ISSUE THREAD

**Issue by lumiera** [rlcevg/CircuitAI#6]
See http://zero-k.info/Battles/Detail/389973 at the very beginning (5-10 seconds into the match).

**Comment by rlcevg** [comment]
Meh. At this point of development blame ZK-devs who allowed plopping factory on top of unit's head. And the author of new fancy startboxes, who decided to break AI's ability to choose own start position.

Though factory build site improvement is somewhere on the bottom of todo list, so i'll leave this report open so far.

**Comment by Anarchid** [comment]
Create a ZK issue for the startpos picking to be fixified?

**Comment by rlcevg** [comment]
Or just reopen already known issue https://github.com/ZeroK-RTS/Zero-K/issues/905?

**Comment by rlcevg** [comment]
https://github.com/rlcevg/CircuitAI/commit/85606635fefa4ab44351527a2bbf374676c2f21d improves situation!

**Comment by rlcevg** [comment]
There were several improvements on topic. Haven't seen traps for a long time.
