### ISSUE TITLE
crash (SIGFPE) in IFighterTask::OnUnitDamaged

### ISSUE THREAD

**Issue by cleanrock** [rlcevg/CircuitAI#7]
spring 100.0.1-1191-gc91bcd6 debug
CircuitAI v0.8.1-3-g36a6b99

I suspect IFighterTask::target points to something that has been deleted.
It looks like you only delete CEnemyUnit in CCircuitAI::UnregisterEnemyUnit and CCircuitAI::UpdateEnemyUnits(), perhaps you don't set IFighterTask::target to nullptr properly when a CEnemyUnit is deleted.

` 
(gdb) bt
#0  0x00007f8e0834c3ce in float3::SqDistance2D (this=0x7f8e05d43450, f=...) at /home/johanr/my_projects/spring/rts/System/float3.h:630
#1  0x00007f8e084b2a69 in circuit::IFighterTask::OnUnitDamaged (this=0x7f8e1de17680, unit=0x7f8e0c7bcf70, attacker=0x0)
    at /home/johanr/my_projects/spring/AI/Skirmish/CircuitAI/src/circuit/task/fighter/FighterTask.cpp:101
#2  0x00007f8e08371291 in circuit::CMilitaryManager::CMilitaryManager(circuit::CCircuitAI*)::{lambda(circuit::CCircuitUnit*, circuit::CEnemyUnit*)#6}::operator()(circuit::CCircuitUnit*, circuit::CEnemyUnit*) const () at /home/johanr/my_projects/spring/AI/Skirmish/CircuitAI/src/circuit/module/MilitaryManager.cpp:114
#3  0x00007f8e0837655c in std::_Function_handler<void(circuit::CCircuitUnit*, circuit::CEnemyUnit*), circuit::CMilitaryManager::CMilitaryManager(circuit::CCircuitAI*)::<lambda(circuit::CCircuitUnit*, circuit::CEnemyUnit*)> >::_M_invoke(const std::_Any_data &, <unknown type in /home/johanr/spring_develop_debug/share/games/spring/AI/Skirmish/CircuitAI/0.8.1/libSkirmishAI.so, CU 0xabc2d, DIE 0x1292fc>, <unknown type in /home/johanr/spring_develop_debug/share/games/spring/AI/Skirmish/CircuitAI/0.8.1/libSkirmishAI.so, CU 0xabc2d, DIE 0x129301>) (__functor=..., 
    __args#0=<unknown type in /home/johanr/spring_develop_debug/share/games/spring/AI/Skirmish/CircuitAI/0.8.1/libSkirmishAI.so, CU 0xabc2d, DIE 0x1292fc>, 
    __args#1=<unknown type in /home/johanr/spring_develop_debug/share/games/spring/AI/Skirmish/CircuitAI/0.8.1/libSkirmishAI.so, CU 0xabc2d, DIE 0x129301>)
    at /usr/include/c++/5.3.0/functional:1871
#4  0x00007f8e0834faa1 in std::function<void (circuit::CCircuitUnit*, circuit::CEnemyUnit*)>::operator()(circuit::CCircuitUnit*, circuit::CEnemyUnit*) const (
    this=0x7f8e04f23d60, __args#0=0x7f8e0c7bcf70, __args#1=0x0) at /usr/include/c++/5.3.0/functional:2267
#5  0x00007f8e08372497 in circuit::CMilitaryManager::UnitDamaged (this=0x7f8e050830d0, unit=0x7f8e0c7bcf70, attacker=0x0)
    at /home/johanr/my_projects/spring/AI/Skirmish/CircuitAI/src/circuit/module/MilitaryManager.cpp:262
#6  0x00007f8e084097e6 in circuit::CCircuitAI::UnitDamaged (this=0x7f8e1dda3cc0, unit=0x7f8e0c7bcf70, attacker=0x0)
    at /home/johanr/my_projects/spring/AI/Skirmish/CircuitAI/src/circuit/CircuitAI.cpp:662
#7  0x00007f8e08405637 in circuit::CCircuitAI::HandleGameEvent (this=0x7f8e1dda3cc0, topic=9, data=0x7fff84f1b1a0)
    at /home/johanr/my_projects/spring/AI/Skirmish/CircuitAI/src/circuit/CircuitAI.cpp:174
#8  0x00007f8e08404cc8 in circuit::CCircuitAI::HandleEvent (this=0x7f8e1dda3cc0, topic=9, data=0x7fff84f1b1a0)
    at /home/johanr/my_projects/spring/AI/Skirmish/CircuitAI/src/circuit/CircuitAI.cpp:100
#9  0x00007f8e0854eb28 in handleEvent (skirmishAIId=1, topic=9, data=0x7fff84f1b1a0) at /home/johanr/my_projects/spring/AI/Skirmish/CircuitAI/src/AIExport.cpp:75
#10 0x0000000000bcfa4a in CSkirmishAILibrary::HandleEvent (this=0x42757a0, skirmishAIId=1, topic=9, data=0x7fff84f1b1a0)
    at /home/johanr/my_projects/spring/rts/ExternalAI/SkirmishAILibrary.cpp:94
#11 0x0000000000bd470f in CSkirmishAIWrapper::HandleEvent (this=0x7f8e1b898a00, topic=9, data=0x7fff84f1b1a0)
    at /home/johanr/my_projects/spring/rts/ExternalAI/SkirmishAIWrapper.cpp:471
#12 0x0000000000bd41dd in CSkirmishAIWrapper::UnitDamaged (this=0x7f8e1b898a00, unitId=5244, attackerUnitId=-1, damage=11.2414055, dir=..., weaponDefId=1081, paralyzer=false)
    at /home/johanr/my_projects/spring/rts/ExternalAI/SkirmishAIWrapper.cpp:348
#13 0x0000000000b9fa4d in CEngineOutHandler::UnitDamaged (this=0x26c3480, damaged=..., attacker=0x0, damage=11.2414055, weaponDefID=1081, projectileID=-1, paralyzer=false)
    at /home/johanr/my_projects/spring/rts/ExternalAI/EngineOutHandler.cpp:456
#14 0x0000000000f03d0b in CUnit::DoDamage (this=0x7f8e1a038000, damages=..., impulse=..., attacker=0x0, weaponDefID=1081, projectileID=-1)
    at /home/johanr/my_projects/spring/rts/Sim/Units/Unit.cpp:1386
`
(gdb) p target->pos 
$13 = {
  <float3> = {
    static CMP_EPS = 9.99999975e-05, 
    static NORMALIZE_EPS = 9.99999996e-13, 
    static maxxpos = 10239, 
    static maxzpos = 5119, 
    {
      {
        x = 2.01941671e-19, 
        y = 2.90873529e+32, 
        z = 2.47243338e+32
      }, 

(gdb) p target->unit 
$14 = (springai::Unit *) 0x57

(gdb) p target->unit->GetDef()
Cannot access memory at address 0x57

**Comment by rlcevg** [comment]
Bummer. Thanks!
Now i remember why i was avoiding target member variable and use only local var.
But it should be a good idea to track tasks inside CEnemyUnit - opens a way for more sophisticated task creation/distribution.

**Comment by rlcevg** [comment]
https://github.com/rlcevg/CircuitAI/commit/5579527069f7ab0a1d8b7718d7545b1abc83be39
