### ISSUE TITLE
Circuit has large CPU spikes on Detriment mission

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#71]
Massive spikes in CPU usage reliably occur in the Detriment mission, making it fairly unplayable. Peaks have gone as high as 64% CPU usage. https://youtu.be/h0r7zUv4vmM

The video uses the most recent dev version of the mission that has a reduced number of circuits and units. The current stable version has more circuits but they do the same thing. The issue does not occur in the Scythe mission, with AI CPU usage peaking rarely at 12% for me.

**Comment by GoogleFrog** [comment]
You cannot. With devmode.txt in your root folder and a zk.sdd you can enable dev mode in settings and skip missions.

**Comment by rlcevg** [comment]
The nightmare came true: https://github.com/rlcevg/CircuitAI/issues/14
Good news is that CBuilderManager::MakeTask seems to be the only source of lag spikes.
