### ISSUE TITLE
Circuit needs rebuilding for dev engine

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#74]
If we are to use the dev engine then circuit requires rebuilding. This creates difficulties as I don't want to be stuck on a particular version depending on circuit.

https://github.com/ZeroK-RTS/CrashReports/issues/3611

**Comment by GoogleFrog** [comment]
In any case, could circuit be built with the new engine and PRed to zkmenu? We can then figure out if any special switching is required.

**Comment by rlcevg** [comment]
I'll be able to recompile in about 12 hours from now.
