### ISSUE TITLE
Circuit does not know what to do about Dominatrix

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#75]
Circuit seems to assume that Dominatrix are harmless. This causes it to lose to a snowball of captured units.

**Comment by rlcevg** [comment]
True, [preparations](https://github.com/spring/spring/pull/354) were made for implementing capture damage, but i had no time since than. Will try to address the issue next weekend.

**Comment by rlcevg** [comment]
https://github.com/rlcevg/CircuitAI/commit/c6a2deae993ecb0b5a11392d4bc880080d03c9b5, kind of... can't test atm

**Comment by rlcevg** [comment]
Tweaked magic numbers a bit https://github.com/rlcevg/CircuitAI/commit/0327c501f36959cb1f6331ab1c3529dfad23fbf2, seems to work better now
