### ISSUE TITLE
Circuit error

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#76]
[infolog.txt](https://github.com/rlcevg/CircuitAI/files/1884604/infolog.txt)

There is an error in this infolog. I have cold feet and don't want to risk a further update prior to release.

**Comment by rlcevg** [comment]
[f=-000001] Skirmish AI <Circuit Normal-stable>: Circuit Normal 0.9.24 (5) Initialized!
What 0.9.24 has to do with latest 1.0.0 version? Also there're no sign of CircuitAI error (no SkirmishAI.dll in stacktraces)

**Comment by rlcevg** [comment]
[f=-000001] Warning: [Watchdog] Hang detection triggered for Spring 104.0.1-358-gb58f0bb maintenance.
Provided infolog contains hang detections that happen prior to AI load procedure (somewhere near Synced LuaRules).
Also old/wrong AI was tested.
Double checked infolog.txt and i see no sign of AI errors.
