### ISSUE TITLE
Circuit breaks on mods of Zero-K

### ISSUE THREAD

**Issue by Histidine91** [rlcevg/CircuitAI#78]
I made a [test mod](https://drive.google.com/file/d/1WlnSPyUR7b_XQfIgpZAYhED-o4XuaUqq/view?usp=sharing) (using Spring's mutator system) for Zero-K. Running it with Circuit and Spring 104.0.1-287-gf7b0fcc or or 104.0.1-358-gb58f0bb causes a segfault.

Infolog: http://paste.springfiles.com/view/02c295f5

(change the modinfo.lua dependency if needed)

What I'd like is:

1. Make it fail more gracefully
2. Allow it to support mods of Zero-K

**Comment by rlcevg** [comment]
AI should fail more gracefully (without crash).
Next line indicates that initialization was rejected and AI supposed to bail out:
```[f=-000001] Skirmish AI <CircuitAIBeginner64-stable>: Zero-K must be 1.5.10.3 or higher! (v0.1)```
But for reason i don't yet understand - it crashed for provided infolog.
Note: can't reproduce with Circuit 1.0.1 but there were no changes in initialization between 0.9.24 and 1.0.1, so the crash is still weird.

**Comment by Anarchid** [comment]
> Have to remove game and version checks inside CircuitAI then.

That could be an AIOption, perhaps?

**Comment by GoogleFrog** [comment]
I think removing the game and version checks is ok if it fails gracefully. 1.5.10.3 is six months old.

**Comment by rlcevg** [comment]
Disabled mod-check:
https://github.com/rlcevg/CircuitAI/commit/641303c3750f0c05df7181116a090aeca13facef
