### ISSUE TITLE
no Caretakers built near factories with ZK 1.4.2.13

### ISSUE THREAD

**Issue by cleanrock** [rlcevg/CircuitAI#8]
This is just a fyi, perhaps a ZK issue.

**Comment by rlcevg** [comment]
Airpad got isBuilder tag and circuit decides that airpad is caretaker.
Probably caretaker, pylon, terraunit and mex should be hardcoded in config (instead of auto-recognition).

https://github.com/rlcevg/CircuitAI/commit/a5085f9fbd4df841e296b58644c750e464efa204
