### ISSUE TITLE
Make a dev circuit for chobby

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#82]
To better handle circuit updates I think we need to package a dev version of circuit in chobby. This would be the latest build and would also be built for the latest engine. Most of the work would be chobby-side. This ticket is mostly to put forth the idea.

**Comment by rlcevg** [comment]
104.0.1-527-gf2536df++ compiled with gcc 5.4 (and probably new ABI). Current stable 104.0.1-287-gf7b0fcc was compiled with gcc 4.8 and old ABI.
Have to update and test build-VMs for linux32, linux64, win32, win64.

**Comment by rlcevg** [comment]
Binary is bundled with spring now:
https://github.com/spring/spring/commit/ce929ecc68726d7cd54a184712eaf9fad0573be1
