### ISSUE TITLE
build fails on debian testing

### ISSUE THREAD

**Issue by Jamanno** [rlcevg/CircuitAI#9]
I followed your installation guide from README..
http://pastebin.com/ks1921Cs
any more info needed?

**Comment by rlcevg** [comment]
try to checkout latest stable version
$ git checkout v0.8.2

Last commits are for spring 102 (not compatible with 100)

**Comment by rlcevg** [comment]
https://github.com/rlcevg/CircuitAI/commit/1a9add1215dce427400825b36e495602a6846409
