### ISSUE TITLE
Dev engine circuit does not use its combat units

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#91]
It makes units but does nothing with them. The only units I have seen it use are constructors and artillery.

[circuitAIandReplay.zip](https://github.com/rlcevg/CircuitAI/files/2560598/circuitAIandReplay.zip)

**Comment by rlcevg** [comment]
last working engine: 104.0.1-822-gcf9c812 maintenance
first broken engine that runs: 104.0.1-828-ga312ff3 maintenance
Most likely the issues is in https://github.com/spring/spring/commit/22b3fe73ca50a8341d7077a195bb24deaf05cd7f
Did they removed ability of an AI to control speed of own units?

**Comment by GoogleFrog** [comment]
CMD.SET_WANTED_MAX_SPEED has been removed entirely. As far as I can tell there is no way in the default engine for AIs (or LuaUI) to set the speed of units. Could you add compatibility for the removal of this ability within Circuit? Backwards compatibility would be best.

**Comment by Anarchid** [comment]
AFAICT the reason Circuit wants to use this command is to keep shieldblobs together. It can use it using staggered move commands or circle-guard though (@aeonios used the latter approach for KGB)

**Comment by rlcevg** [comment]
From latest [spring maintenance](https://github.com/spring/spring/commit/0b800f18e7c8356364c434ea0f6e95b13dc9169e) Circuit should work again (though it doesn't control speed anymore)
