### ISSUE TITLE
Feature: Merge configs

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#93]
I would be easier to maintain updates for multiple difficulty levels if circuit read every json file in /configs and merged the resulting table.

**Comment by rlcevg** [comment]
Note to myself:
1) remove easy and hard sections from json config and AIOptions.lua
2) add isCheating param into AIOptions.lua
3) read in alphabetical order all .json files from /configs into single in-memory config, with possible single param overrides and section additions.

**Comment by rlcevg** [comment]
There are no AI API to list files in directory.

**Comment by rlcevg** [comment]
https://github.com/rlcevg/CircuitAI/commit/31800727b94f1eabad73edd7f5cfe3287cf5c57b
```
AIOptions.lua
config_file=behaviour+block_map+build_chain+commander+economy+factory+response
```
And Circuit will load behaviour.json, then block_map.json, then build_chain.json, etc. in order of appearance inside config_file param.
