### ISSUE TITLE
Circuit crashes

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#96]
Here are some crashes with stacktraces from within circuit.
- https://github.com/ZeroK-RTS/CrashReports/issues/20534
- https://github.com/ZeroK-RTS/CrashReports/issues/20545
- https://github.com/ZeroK-RTS/CrashReports/issues/20548

**Comment by rlcevg** [comment]
https://github.com/spring/spring/commit/1415b9be7008581760a69609adc5633386c89eab
https://github.com/spring/spring/commit/9c151887971c19c40cdd88dbf085f1638c9e5bfa

Those engine changes may already fixed it.

**Comment by rlcevg** [comment]
old data/engine
