### ISSUE TITLE
104.0.1-1156-gb72a9cc AI crashes

### ISSUE THREAD

**Issue by GoogleFrog** [rlcevg/CircuitAI#98]
https://github.com/ZeroK-RTS/CrashReports/issues/21086
https://github.com/ZeroK-RTS/CrashReports/issues/21088

**Comment by rlcevg** [comment]
stacktranslate.springrts.com doesn't work

**Comment by GoogleFrog** [comment]
Could you make a mantis ticket about that?

**Comment by rlcevg** [comment]
rusty gdb skillz:
ZeroK-RTS/CrashReports#21086
```
(gdb) info line *0x6B42DA24
Line 161 of "/home/buildbot/mxe/usr/lib/gcc/i686-w64-mingw32.static.posix/5.5.0/include/c++/bits/stl_vector.h" starts at address 0x6b42da24 <circuit::CSuperTask::Update()+5476>
   and ends at 0x6b42da2a <circuit::CSuperTask::Update()+5482>.
```
ZeroK-RTS/CrashReports#21088
```
(gdb) info line *0x6B42D5B5
Line 66 of "../../AI/Skirmish/CircuitAI/src/circuit/task/static/SuperTask.cpp" starts at address 0x6b42d58d <circuit::CSuperTask::Update()+4301>
   and ends at 0x6b42d5b8 <circuit::CSuperTask::Update()+4344>.
```
Can't see much sense, worth testing units with superweapon role ("shieldshield"???, "raveparty", "staticnuke", "staticheavyarty", "zenith").
Another save/load corruption?

**Comment by rlcevg** [comment]
WRT stacktranslate
https://springrts.com/mantis/view.php?id=6191

**Comment by rlcevg** [comment]
outdated
