### ISSUE TITLE
Crash on 104.0.1-1239-g12caea1

### ISSUE THREAD

**Issue by Histidine91** [rlcevg/CircuitAI#99]
[Report](https://github.com/ZeroK-RTS/CrashReports/issues/22246)

[Steam thread](https://steamcommunity.com/app/334920/discussions/1/1644290549109385135/)

**Comment by rlcevg** [comment]
notes:
1) why thread says that there're only 2 AI (skirmish + chicken), but infolog shows 2 skirmish and 1 chicken?
2) what kind of mutators and modoptions were used?
3) what happened to 2nd skirmish AI at 10th second that was never meant to be in this game?
```
[f=0000306] game_message: AI has been destroyed!
[f=0000319] [EOH::DestroySkirmishAI(id=1)]
[f=0000332] [Game::ClientReadNet] local skirmish AI "AI: Brutal (2)" (ID: 1) being removed from team 2
```

**Comment by Histidine91** [comment]
Poster replied:

> 1. there were indeed 2 AI's but 1 AI spawned next to us for some reason and was killed instantly so didn't have much impact on the game.
> 2. only for the second game, terraform cost 0.01 and metal and energy were on 2 I think
> 3. see remark 1

**Comment by rlcevg** [comment]
old data, also possibly fixed by https://github.com/rlcevg/CircuitAI/commit/47098540728135f6e3d3ed6ec666a14dc03e0664
